### ISSUE TITLE
test_iput_with_metadata_overwrite__issue_3114 fails consistently on openSUSE

### ISSUE THREAD

**Issue by jassigill2000** [irods/irods_testing_jenkins#105]
```
======================================================================
ERROR [8.080s]: test_iput_with_metadata_overwrite__issue_3114 (irods.test.test_iput_options.Test_iPut_Options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_iput_options.py", line 63, in test_iput_with_metadata_overwrite__issue_3114
    self.admin.assert_icommand('iput -f --metadata "a;v;u" ' + filepath)
  File "/var/lib/irods/scripts/irods/test/session.py", line 159, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

```
Jun 17 17:33:28 pid:1373 remote addresses: 192.168.0.2, 192.168.144.2 ERROR: iRODS Exception:
    file: /irods_git_repo/server/core/src/miscServerFunct.cpp
    function: void applyMetadataFromKVP(rsComm_t *, dataObjInp_t *)
    line: 3221
    code: -806000 (CAT_SQL_ERR)
    message:
        rsModAVUMetadata failed
stack trace:
--------------

Dumping stack trace
<0>     Offset: 0x6e    Address: 0x7fcd9771a74e irods::exception::exception(long, std::__1::basic_string<char, std::__1::char_traits<char>,
 std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned
 int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<1>     Offset: 0x3ee   Address: 0x7fcd9a91d41e applyMetadataFromKVP(rsComm_t*, DataObjInp*)
<2>     Offset: 0xbc9   Address: 0x7fcd9a577dd9 _rsDataObjClose(rsComm_t*, OpenedDataObjInp*)
<3>     Offset: 0x12a   Address: 0x7fcd9a5769ba irsDataObjClose(rsComm_t*, OpenedDataObjInp*, DataObjInfo**)
<4>     Offset: 0xc3    Address: 0x7fcd9a5867d3 l3DataPutSingleBuf(rsComm_t*, DataObjInp*, BytesBuf*)
<5>     Offset: 0x61    Address: 0x7fcd9a5864c1 _rsDataObjPut(rsComm_t*, DataObjInp*, BytesBuf*, portalOprOut**)
<6>     Offset: 0x771   Address: 0x7fcd9a5861a1 rsDataObjPut(rsComm_t*, DataObjInp*, BytesBuf*, portalOprOut**)
<7>     Offset: 0x6a    Address: 0x7fcd9a79ae8a irods::api_call_adaptor<DataObjInp*, BytesBuf*, portalOprOut**>::operator()(irods::plugin_c
ontext&, rsComm_t*, DataObjInp*, BytesBuf*, portalOprOut**)
<8>     Offset: 0x26    Address: 0x7fcd9a79ade6 std::__1::__function::__func<irods::api_call_adaptor<DataObjInp*, BytesBuf*, portalOprOut**
>, std::__1::allocator<irods::api_call_adaptor<DataObjInp*, BytesBuf*, portalOprOut**> >, irods::error (irods::plugin_context&, rsComm_t*, 
DataObjInp*, BytesBuf*, portalOprOut**)>::operator()(irods::plugin_context&, rsComm_t*&&, DataObjInp*&&, BytesBuf*&&, portalOprOut**&&)
<9>     Offset: 0xd17   Address: 0x7fcd9a68caa7 int irods::api_entry::call_handler<DataObjInp*, BytesBuf*, portalOprOut**>(rsComm_t*, DataObjInp*, BytesBuf*, portalOprOut**)
<10>    Offset: 0x73a   Address: 0x7fcd9a93e11a rsApiHandler(rsComm_t*, int, BytesBuf*, BytesBuf*)
<11>    Offset: 0xa4b   Address: 0x7fcd9a9401bb readAndProcClientMsg(rsComm_t*, int)
<12>    Offset: 0xd08   Address: 0x7fcd9a9310d8 agentMain(rsComm_t*)
<13>    Offset: 0x1fa5  Address: 0x7fcd9a92f325 runIrodsAgentFactory(sockaddr_un)
<14>    Offset:         Address: 0x42905d       /usr/sbin/irodsServer(main+0x4cd) [0x42905d]
<15>    Offset:         Address: 0x7fcd96bef34a /lib64/libc.so.6(__libc_start_main+0xea) [0x7fcd96bef34a]
<16>    Offset:         Address: 0x428ada       /usr/sbin/irodsServer(_start+0x2a) [0x428ada]
```

**Comment by trel** [comment]
please capture the SQL that's firing in the server.
